In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

### Properities and Attributes

In [16]:
arr8=np.array([[[1,2],[2,3]],[[3,4],[4,6]]])
arr8

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 6]]])

In [17]:
arr8.shape

(2, 2, 2)

In [18]:
arr2.ndim

2

In [19]:
arr1.size

4

In [20]:
arr8.itemsize

4

In [26]:
arr8.astype('float')

array([[[1., 2.],
        [2., 3.]],

       [[3., 4.],
        [4., 6.]]])

#### LIST VS ARRAY

In [28]:
list1=range(100)
arr_new=np.arange(100)

In [29]:
import sys

In [32]:
print(sys.getsizeof(87)*len(list1))

2800


In [33]:
print(arr_new.itemsize*arr_new.size)

400


In [34]:
import time

In [36]:
x=range(100000000)
y=range(100000000)

start_time=time.time()

c=[(x,y) for x,y in zip(x,y)]
print(time.time()-start_time)

24.976813077926636


In [37]:
a=np.arange(100000000)
b=np.arange(100000000)
start_time=time.time()

c=a+b

print(time.time()-start_time)

19.178462982177734


### Indexing Slicing Iteration


In [39]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [81]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [80]:
 arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [42]:
arr12[:,2] # we want to print 2,  6, 10, 14, 18, 22

array([ 2,  6, 10, 14, 18, 22])

In [43]:
arr12[:,1:3] # 2nd and 3rd col

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [45]:
arr12[:2]

array([[0, 1, 2, 3]])

In [75]:
arr12[2,2]

10

#### indexing

In [49]:
var1=np.array([1,2,3])
var1

array([1, 2, 3])

In [51]:
var2=np.array([[1,2,5],[3,4,9]])
var2

array([[1, 2, 5],
       [3, 4, 9]])

In [52]:
var2[0,1] #getting 2

2

In [53]:
var2[1,2] # getting 9

9

In [58]:
var3=np.array([[[1,2],[3,4]]])

In [59]:
var3

array([[[1, 2],
        [3, 4]]])

In [61]:
var3[0,1,1]

4

In [62]:
var3[0,0,1]

2

#### slicing

In [66]:
varx=np.array([[1,2,5,65,88],[3,4,97,33,46],[12,13,14,15,16]])
varx

array([[ 1,  2,  5, 65, 88],
       [ 3,  4, 97, 33, 46],
       [12, 13, 14, 15, 16]])

In [67]:
varx[1,1:]

array([ 4, 97, 33, 46])

In [69]:
varx[:,2]

array([ 5, 97, 14])